version: "3"
services:
  php:
    container_name: php74
    build: ./php
    volumes:
      - ./src:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: 
      - "postgresql"
  nginx:
    container_name: nginxlatest
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    depends_on: 
      - "php"
    ports:
      - "80:80"
  postgresql:
    container_name: postgresql
    image: postgres:14
    user: postgres
    environment:
      POSTGRES_PASSWORD: passw0rd
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./pgsql-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"